name: Lint and test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CF_SKIP_SETUP: "true"
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@master

      - name: Init columnflow submodule
        run: git submodule update --init modules/columnflow

      - name: Setup python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies ☕️
        run: |
          export CF_SKIP_SETUP="true"
          source setup.sh ""

      - name: Lint 🔍
        run: |
          export CF_SKIP_SETUP="true"
          source setup.sh ""
          ./tests/run_linting

